id: P003160
initial_creation_type: ocr
source_metadata:
  id: bdr:W16470
  title: བློ་བཟང་དཔལ་ལྡན་བསྟན་འཛིན་སྙན་གྲགས་དཔལ་བཟང་པོའི་རྣམ་ཐར
  author: ''
  volumes:
    72a54eb6371644d0963fb33500362cc2:
      image_group_id: I1CZ1014
      title: ''
      volume_number: 1
      total_pages: 662
      base_file: v001.txt
