id: P003160
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W16470
  title: བློ་བཟང་དཔལ་ལྡན་བསྟན་འཛིན་སྙན་གྲགས་དཔལ་བཟང་པོའི་རྣམ་ཐར
  author: ''
  volumes:
    72a54eb6371644d0963fb33500362cc2:
      image_group_id: I1CZ1014
      title: ''
      volume_number: 1
      total_pages: 662
      base_file: v001.txt
